### ISSUE TITLE
Audio playback cuts out intermittently when switching to a different tab in Chrome

### ISSUE THREAD

**Issue by meyer** [audionerd/byte-music.js#2]
Happens in Chrome 46 beta, might be because it’s a beta (though they are usually quite stable).

Update: it doesn’t cut out, it just gets suuuuper slow.

**Comment by audionerd** [comment]
Good point. The scheduling is currently very naive, using a simple `setTimeout`, which Chrome will throttle back whenever the tab isn't active. A better solution would be to use Web Audio scheduling for all events.
